# Generated by Django 5.1.3 on 2025-02-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_studymaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studymaterials_name', models.CharField(max_length=50)),
                ('studymaterials_details', models.CharField(max_length=50)),
                ('studymaterials_file', models.FileField(upload_to='assets/teacher/photo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
