# Generated by Django 5.1.3 on 2025-02-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_studymaterials',
        ),
    ]
