# Generated by Django 5.1.3 on 2025-03-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_teacher'),
        ('Teacher', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questionbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionbody_question', models.CharField(max_length=50)),
                ('questionbody_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_classvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=50)),
                ('class_desc', models.CharField(max_length=50)),
                ('class_file', models.FileField(upload_to='assets/teacher/photo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_choice', models.CharField(max_length=50)),
                ('option_status', models.CharField(max_length=50)),
                ('questionbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_questionbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questionhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qhead_title', models.CharField(max_length=50)),
                ('qhead_score', models.IntegerField()),
                ('qhead_status', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
