# Generated by Django 5.1.3 on 2025-03-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_teacher'),
        ('Teacher', '0004_tbl_questionbody_tbl_classvideo_tbl_option_and_more'),
        ('User', '0009_remove_tbl_answerhead_questionbody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_questionhead',
            name='teacher',
        ),
        migrations.CreateModel(
            name='tbl_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=50)),
                ('examination_mark', models.CharField(max_length=50)),
                ('examination_qno', models.CharField(max_length=50)),
                ('examination_time', models.CharField(max_length=50)),
                ('examination_status', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_examination')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_questions')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_option',
        ),
        migrations.DeleteModel(
            name='tbl_questionbody',
        ),
        migrations.DeleteModel(
            name='tbl_questionhead',
        ),
    ]
