# Generated by Django 5.1.3 on 2025-01-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teacher',
            name='place',
        ),
    ]
