# Generated by Django 5.1.3 on 2025-01-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_subject_delete_tbl_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_email', models.CharField(max_length=50)),
                ('teacher_contact', models.CharField(max_length=50)),
                ('teacher_address', models.CharField(max_length=50)),
                ('teacher_password', models.CharField(max_length=50)),
                ('teacher_photo', models.FileField(upload_to='assets/teacher/photo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
