# Generated by Django 5.2 on 2025-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teacher',
            name='teacher_url',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
