# Generated by Django 5.2 on 2025-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_teacher_teacher_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teacher',
            name='teacher_class_status',
            field=models.IntegerField(default=0),
        ),
    ]
