from django.urls import path,include
from Admin import views
from User.models import *
app_name="Admin"
urlpatterns = [
   path('add/',views.add,name='add'), 
   path('largest/',views.largest,name='largest'),
   path('calculator/',views.calculator,name='calculator'),
   path('district/',views.district,name='district'),
   path('category/',views.category,name='category'),
   path('AdminReg/',views.adminreg,name='AdminReg'),
   path('adelete/<int:id>',views.adelete,name='adelete'),
   path('ddelete/<int:id>',views.ddelete,name='ddelete'),
   path('place/',views.place,name="place"),
   path('brand/',views.brand,name="brand"),
   path('bdelete/<int:id>',views.bdelete,name='bdelete'),
   path('bedit/<int:id>',views.bedit,name='bedit'),
   path('pdelete/<int:id>',views.pdelete,name='pdelete'),
   path('subcategory/',views.subcategory,name="subcategory"),
   path('cdelete/<int:id>',views.cdelete,name='cdelete'),
   path('cedit/<int:id>',views.cedit,name='cedit'),
   path('teacher/',views.teacher,name='teacher'),
   path('subject/',views.subject,name='subject'),
   path('sdelete/<int:id>',views.sdelete,name='sdelete'),
   path('Viewteacher/',views.Viewteacher,name="Viewteacher"),
   path('Viewuser/',views.Viewuser,name="Viewuser"),
   path('homepage/',views.homepage,name="homepage"),
   path('useraccept/<int:id>',views.useraccept,name="useraccept"),
   path('userreject/<int:id>',views.userreject,name="userreject"),
   path('accepteduser/',views.accepteduser,name="accepteduser"),
   path('rejecteduser/',views.rejecteduser,name="rejecteduser"),
   # path('teacheraccept/<int:id>',views.teacheraccept,name="teacheraccept"),
   path('teacherreject/<int:id>',views.teacherreject,name="teacherreject"),
   path('acceptedteacher/',views.acceptedteacher,name="acceptedteacher"),
   path('rejectedteacher/',views.rejectedteacher,name="rejectedteacher"),
   path('complaint/',views.complaint,name="complaint"),
   path('replycomplaint/<int:id>',views.replycomplaint,name="replycomplaint"),
   path('Viewfeedbacks/',views.Viewfeedbacks,name="Viewfeedbacks"),
]