# Generated by Django 5.1.3 on 2025-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
        ('Guest', '0002_tbl_reg_delete_tbl_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_reg',
            new_name='tbl_user',
        ),
    ]
