# Generated by Django 5.1.3 on 2025-03-17 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_teacher'),
        ('Guest', '0004_tbl_user_user_status'),
        ('Teacher', '0004_tbl_questionbody_tbl_classvideo_tbl_option_and_more'),
        ('User', '0007_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_answerbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerbody_status', models.CharField(max_length=50)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_option')),
                ('questionbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_questionbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_answerhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_questionbody')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('teacher_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_from', to='Admin.tbl_teacher')),
                ('teacher_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_to', to='Admin.tbl_teacher')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
