# Generated by Django 5.1.3 on 2025-03-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_answerbody_tbl_answerhead_tbl_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_answerhead',
            name='questionbody',
        ),
        migrations.RemoveField(
            model_name='tbl_answerhead',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_answerbody',
        ),
        migrations.DeleteModel(
            name='tbl_answerhead',
        ),
    ]
