# Generated by Django 5.1.3 on 2025-03-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_user_user_status'),
        ('Teacher', '0005_remove_tbl_questionhead_teacher_tbl_examination_and_more'),
        ('User', '0009_remove_tbl_answerhead_questionbody_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_examination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='Teacher.tbl_options')),
                ('myanswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='Teacher.tbl_options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_questions')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timmer', models.TimeField()),
                ('timmer_status', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_examination')),
            ],
        ),
    ]
